CREATE TABLE `kob_job_cron_incubator` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `project_code` varchar(60) NOT NULL DEFAULT '' COMMENT '项目唯一标识',
  `project_name` varchar(60) NOT NULL DEFAULT '' COMMENT '项目中文名称',
  `job_uuid` varchar(60) NOT NULL DEFAULT '' COMMENT '作业唯一标识',
  `job_type` varchar(64) NOT NULL DEFAULT '' COMMENT '作业类型',
  `job_cn` varchar(60) NOT NULL DEFAULT '' COMMENT '作业中文名称',
  `task_key` varchar(60) NOT NULL DEFAULT '' COMMENT '任务标识,客户端而得的',
  `task_type` varchar(60) NOT NULL DEFAULT '' COMMENT '任务类型',
  `task_remark` varchar(60) NOT NULL DEFAULT '' COMMENT '任务备注',
  `load_balance` varchar(60) NOT NULL DEFAULT '' COMMENT '负载均衡策略',
  `suspend` int(6) DEFAULT NULL COMMENT '是否处于暂停状态 1是、0否',
  `batch_type` varchar(60) NOT NULL DEFAULT '' COMMENT '是否批处理作业 1是、0否',
  `retry_type` varchar(60) NOT NULL DEFAULT '' COMMENT '重试类型 0不重试、1失败重试，2超时重试，12失败超时均重试',
  `failover` int(6) DEFAULT NULL COMMENT '故障转移',
  `rely` int(6) DEFAULT NULL COMMENT '是否依赖上一周期 1是、0否',
  `cron_expression` varchar(128) NOT NULL DEFAULT '' COMMENT 'Cron表达式',
  `user_params` text COMMENT '自定义参数，可用于分片',
  `inner_params` text COMMENT '内部扩展参数',
  `last_generate_trigger_time` bigint(20) DEFAULT NULL COMMENT '最后生成的带推送任务的triggerTime时间',
  `timeout_threshold` bigint(20) DEFAULT NULL COMMENT '超时阈值，单位分钟',
  `retry_count` int(6) DEFAULT NULL COMMENT '失败重试次数',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  `gmt_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据库创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据库更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_job_uuid` (`job_uuid`) USING BTREE COMMENT '唯一索引:作业uuid',
  KEY `idx_last_generate_trigger_time` (`last_generate_trigger_time`) USING BTREE COMMENT '普通索引:最后生成时间',
  KEY `idx_project_code` (`project_code`) USING BTREE COMMENT '普通索引:项目标识'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='cron作业表';

CREATE TABLE `kob_task_record_incubator` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `project_code` varchar(60) NOT NULL DEFAULT '' COMMENT '项目唯一标识',
  `project_name` varchar(60) NOT NULL DEFAULT '' COMMENT '项目中文名称',
  `job_uuid` varchar(60) NOT NULL DEFAULT '' COMMENT '作业唯一标识',
  `job_type` varchar(60) NOT NULL DEFAULT '' COMMENT '作业类型',
  `job_cn` varchar(60) NOT NULL DEFAULT '' COMMENT '作业中文名称',
  `task_key` varchar(60) NOT NULL DEFAULT '' COMMENT '任务标识,客户端而得的',
  `task_remark` varchar(60) NOT NULL DEFAULT '' COMMENT '任务备注',
  `task_type` varchar(60) NOT NULL DEFAULT '' COMMENT '任务类型',
  `task_uuid` varchar(60) NOT NULL DEFAULT '' COMMENT '任务唯一标识',
  `relation_task_uuid` varchar(60) NOT NULL DEFAULT '' COMMENT '依赖任务标识，用于串联任务执行情况',
  `retry_type` varchar(60) NOT NULL DEFAULT '' COMMENT '重试类型 0不重试、1失败重试，2超时重试，12失败超时均重试',
  `rely` int(6) DEFAULT NULL COMMENT '是否依赖上一周期 1是、0否',
  `ancestor` int(6) DEFAULT NULL COMMENT '是否是任务源头 1是、0否',
  `user_params` text COMMENT '用户参数 JSON',
  `inner_params` text COMMENT '内部扩展参数 JSON',
  `msg` text COMMENT '任务返回结果',
  `cron_expression` varchar(128) NOT NULL DEFAULT '' COMMENT 'cron表达式',
  `timeout_threshold` bigint(20) DEFAULT NULL COMMENT '超时阈值,单位分钟',
  `failover` int(6) DEFAULT NULL COMMENT '故障转移',
  `load_balance` varchar(60) NOT NULL DEFAULT '' COMMENT '负载均衡策略',
  `state` int(6) DEFAULT NULL COMMENT '作业状态',
  `complete` int(6) DEFAULT NULL COMMENT '完成状态，只用于展示',
  `retry_count` int(6) DEFAULT NULL COMMENT '失败重试次数',
  `batch_type` varchar(60) NOT NULL DEFAULT '' COMMENT '是否批处理作业 1是、0否',
  `client_identification` varchar(40) NOT NULL DEFAULT '' COMMENT '客户端执行节点',
  `trigger_time` bigint(20) DEFAULT NULL COMMENT '触发时间',
  `consumption_time` datetime DEFAULT NULL COMMENT '消费时间',
  `execute_start_time` datetime DEFAULT NULL COMMENT '开始执行时间',
  `execute_end_time` datetime DEFAULT NULL COMMENT '执行完成时间',
  `version` bigint(20) NOT NULL DEFAULT '0' COMMENT '乐观锁',
  `gmt_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据库创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据库更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_task_uuid` (`task_uuid`) USING BTREE COMMENT '唯一索引:任务标识',
  KEY `idx_trigger_time` (`trigger_time`) USING BTREE COMMENT '普通索引:触发时间',
  KEY `idx_project_code` (`project_code`) USING BTREE COMMENT '普通索引:项目标识',
  KEY `idx_job_uuid` (`job_uuid`) USING BTREE COMMENT '普通索引:作业标识'
) ENGINE=InnoDB AUTO_INCREMENT=45399 DEFAULT CHARSET=utf8mb4 COMMENT='任务一览';

CREATE TABLE `kob_task_waiting_incubator` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `project_code` varchar(60) NOT NULL DEFAULT '' COMMENT '项目唯一标识',
  `project_name` varchar(60) NOT NULL DEFAULT '' COMMENT '项目中文名称',
  `job_uuid` varchar(60) NOT NULL DEFAULT '' COMMENT '作业唯一标识',
  `job_type` varchar(60) NOT NULL DEFAULT '' COMMENT '作业类型',
  `job_cn` varchar(60) NOT NULL DEFAULT '' COMMENT '作业中文名称',
  `task_key` varchar(60) NOT NULL DEFAULT '' COMMENT '任务标识,客户端而得的',
  `task_remark` varchar(60) NOT NULL DEFAULT '' COMMENT '任务备注',
  `task_type` varchar(60) NOT NULL DEFAULT '' COMMENT '任务类型',
  `task_uuid` varchar(60) NOT NULL DEFAULT '' COMMENT '任务唯一标识kob_task_waiting_incubator',
  `relation_task_uuid` varchar(60) NOT NULL DEFAULT '' COMMENT '依赖任务标识，用于串联任务执行情况',
  `retry_type` varchar(60) NOT NULL DEFAULT '' COMMENT '重试类型 0不重试、1失败重试，2超时重试，12失败超时均重试',
  `batch_type` varchar(60) NOT NULL DEFAULT '' COMMENT '是否批处理作业 1是、0否',
  `failover` int(6) DEFAULT NULL COMMENT '故障转移',
  `load_balance` varchar(60) NOT NULL DEFAULT '' COMMENT '负载均衡策略',
  `rely` int(6) DEFAULT NULL COMMENT '是否依赖上一周期 1是、0否',
  `user_params` text COMMENT '用户参数 JSON',
  `inner_params` text COMMENT '内部扩展参数 JSON',
  `cron_expression` varchar(128) NOT NULL DEFAULT '' COMMENT 'cron表达式',
  `timeout_threshold` bigint(20) DEFAULT NULL COMMENT '超时阈值,单位分钟',
  `retry_count` int(6) DEFAULT NULL COMMENT '失败重试次数',
  `trigger_time` bigint(20) DEFAULT NULL COMMENT '触发时间',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  `gmt_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据库创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据库更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_task_uuid` (`task_uuid`) USING BTREE COMMENT '唯一索引:任务标识',
  KEY `idx_trigger_time` (`trigger_time`) USING BTREE COMMENT '普通索引:触发时间',
  KEY `idx_job_uuid` (`job_uuid`) USING BTREE COMMENT '普通索引:作业标识',
  KEY `idx_project_code` (`project_code`) USING BTREE COMMENT '普通索引:项目标识'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='等待执行任务';

CREATE TABLE `kob_user_incubator` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `code` varchar(100) NOT NULL DEFAULT '' COMMENT '用户账号',
  `name` varchar(100) NOT NULL DEFAULT '' COMMENT '用户姓名',
  `pwd` varchar(100) NOT NULL DEFAULT '' COMMENT '密码',
  `configuration` text COMMENT '个人配置信息，预留JSON字段可以存邮箱手机号之类',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  `gmt_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户库，公司级可以通过账户接口替代';

INSERT INTO `kob_user_incubator`(`code`, `name`, `pwd`, `configuration`)
 VALUES ('xiaoming', '小明', 'xiaoming', '{"mail":"xiaoming@ke.com"}');
INSERT INTO `kob_user_incubator`(`code`, `name`, `pwd`, `configuration`)
 VALUES ('xiaohong', '小红', 'xiaohong', '{"mail":"xiaohong@ke.com"}');

CREATE TABLE `kob_log_collect_incubator` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `state` int(6) DEFAULT NULL COMMENT '状态',
  `log_uuid` varchar(60) NOT NULL DEFAULT '' COMMENT '日志唯一标识',
  `project_code` varchar(60) NOT NULL DEFAULT '' COMMENT '项目唯一标识',
  `task_uuid` varchar(60) NOT NULL DEFAULT '' COMMENT '任务唯一标识',
  `log_mode` varchar(60) NOT NULL DEFAULT '' COMMENT '日志模式',
  `log_level` varchar(60) NOT NULL DEFAULT '' COMMENT '日志级别',
  `client_identification` varchar(60) NOT NULL DEFAULT '' COMMENT '客户端执行节点',
  `msg` text COMMENT '任务结果',
  `log_time` datetime DEFAULT NULL COMMENT '日志上报时间',
  `gmt_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据库创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据库更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_project_code` (`project_code`) USING BTREE COMMENT '普通索引:项目标识',
  KEY `idx_task_uuid` (`task_uuid`) USING BTREE COMMENT '普通索引:任务标识'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='收集表';

CREATE TABLE `kob_log_opt_incubator` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_code` varchar(100) NOT NULL DEFAULT '' COMMENT '账号',
  `user_name` varchar(100) NOT NULL DEFAULT '' COMMENT '姓名，用于显示',
  `opt_url` varchar(200) NOT NULL DEFAULT '' COMMENT '操作路径',
  `request` text COMMENT 'request',
  `response` text COMMENT 'response',
  `cost_time` int(11) DEFAULT NULL COMMENT '花费时间',
  `gmt_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据库创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据库更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_cost_time` (`cost_time`) USING BTREE COMMENT '普通索引:耗时'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='操作日志';

CREATE TABLE `kob_project_user_incubator` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_code` varchar(50) NOT NULL DEFAULT '' COMMENT '用户账号',
  `user_name` varchar(100) NOT NULL DEFAULT '' COMMENT '用户姓名',
  `project_code` varchar(100) NOT NULL DEFAULT '' COMMENT '项目标识',
  `project_name` varchar(100) NOT NULL DEFAULT '' COMMENT '项目名称',
  `project_mode` varchar(100) NOT NULL DEFAULT '' COMMENT '项目模式：service||admin',
  `owner` tinyint(1) DEFAULT NULL COMMENT '是否属于某业务线的负责人，默认为0，如果为负责人，则为1',
  `configuration` text COMMENT '个人配置信息，预留JSON字段可以存邮箱手机号之类',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '乐观锁版本',
  `gmt_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_user_code_project_code` (`user_code`,`project_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='项目人员'
